version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      minor-and-patch-dependencies:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "org.junit.jupiter:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.junit.vintage:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.springframework:*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      minor-and-patch-dependencies:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "org.junit.jupiter:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.junit.vintage:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.springframework:*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "gradle"
    directory: "/junit-5-gradle-kotlin/"
    schedule:
      interval: "daily"
    groups:
      minor-and-patch-dependencies:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "org.junit.jupiter:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.junit.vintage:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.springframework:*"
        update-types: ["version-update:semver-major"]
